[features]
seeds = false
skip-lint = false
[programs.localnet]
cross_pay_solana = "EdFNrBQdR4zMvzFh1HopuS5N9z6wjfWubcWpMfAvgWPC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "./keys/id.json" #73U7u2pAKsm7RxKMjbQtHuhh4L94581QQvzWtqKyuqeZ
[test.validator]
faucet_sol = "1500000000000000000" 

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"


# commands
# solana program deploy target/deploy/cross_pay_solana.so 
# anchor keys list 