[features]
seeds = false
skip-lint = false
[programs.localnet]
cross_pay_solana = "GLRu4n249vQNpfPdubfiz4kw2AVV1yUyJ9brLB4crvzd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./keys/id.json" #73U7u2pAKsm7RxKMjbQtHuhh4L94581QQvzWtqKyuqeZ
[test.validator]
faucet_sol = "1500000000000000000" 

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
